<?php
/**
 * Configuration file for Project Linkon
 * Generated by Setup Wizard
 */

return [
    // Database configuration
    'database' => [
        'driver' => 'mysql',
        'host' => 'localhost',
        'port' => '3306',
        'database' => 'linkon',
        'username' => 'root',
        'password' => 'testpassword',
        'charset' => 'utf8mb4',
    ],

    // Encryption configuration
    'encryption' => [
        'method' => 'aes-256-gcm',
        'key' => '76016ac1124e8903f9afe97d10ad2566746f20ea95b3dcf8b02335a41aa5832f',
    ],

    // Application configuration
    'app' => [
        'base_url' => 'http://localhost:8080',
        'link_length' => 8,
        'debug' => false,
        'cors_origin' => '*',
    ],

    // Password hashing configuration
    'password' => [
        'algo' => PASSWORD_ARGON2ID,
        'options' => [
            'memory_cost' => 65536,
            'time_cost' => 4,
            'threads' => 3,
        ],
    ],
];