<?php
/**
 * Setup Wizard
 * 
 * Handles initial application setup including:
 * - Database configuration
 * - Encryption key generation
 * - Database table creation
 * - Configuration file generation
 */

// Prevent access if already configured
$configPath = __DIR__ . '/../config/config.php';
$installedPath = __DIR__ . '/../config/.installed';

// Check if already installed
if (file_exists($installedPath)) {
    header('Location: /');
    exit;
}

// Error reporting for setup
error_reporting(E_ALL);
ini_set('display_errors', 0);

$step = $_GET['step'] ?? 'welcome';
$error = '';
$success = '';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';
    
    if ($action === 'test_database') {
        // Test database connection
        $dbConfig = [
            'host' => $_POST['db_host'] ?? 'localhost',
            'port' => $_POST['db_port'] ?? '3306',
            'database' => $_POST['db_name'] ?? 'linkon',
            'username' => $_POST['db_user'] ?? 'root',
            'password' => $_POST['db_password'] ?? '',
        ];
        
        try {
            $dsn = sprintf(
                "mysql:host=%s;port=%s;charset=utf8mb4",
                $dbConfig['host'],
                $dbConfig['port']
            );
            $pdo = new PDO($dsn, $dbConfig['username'], $dbConfig['password'], [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);
            
            // Try to select the database, create it if it doesn't exist
            try {
                $pdo->exec("USE " . $dbConfig['database']);
            } catch (PDOException $e) {
                // Database doesn't exist, try to create it
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `" . $dbConfig['database'] . "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE " . $dbConfig['database']);
            }
            
            $success = 'Database connection successful!';
            
            // Store config in session for next step
            session_start();
            $_SESSION['setup_db_config'] = $dbConfig;
            
        } catch (PDOException $e) {
            $error = 'Database connection failed: ' . $e->getMessage();
        }
    } elseif ($action === 'complete_setup') {
        session_start();
        $dbConfig = $_SESSION['setup_db_config'] ?? null;
        
        if (!$dbConfig) {
            $error = 'Database configuration not found. Please go back and test the connection.';
        } else {
            try {
                // Connect to database
                $dsn = sprintf(
                    "mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4",
                    $dbConfig['host'],
                    $dbConfig['port'],
                    $dbConfig['database']
                );
                $pdo = new PDO($dsn, $dbConfig['username'], $dbConfig['password'], [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                ]);
                
                // Create tables
                $schema = file_get_contents(__DIR__ . '/../database/schema.sql');
                
                // Split into individual statements and execute
                $statements = array_filter(array_map('trim', explode(';', $schema)));
                foreach ($statements as $statement) {
                    if (!empty($statement) && 
                        stripos($statement, 'CREATE DATABASE') === false && 
                        stripos($statement, 'USE ') === false) {
                        $pdo->exec($statement);
                    }
                }
                
                // Generate encryption key
                $encryptionKey = bin2hex(random_bytes(32));
                
                // Determine base URL
                $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
                $host = $_SERVER['HTTP_HOST'];
                $basePath = dirname($_SERVER['SCRIPT_NAME']);
                $basePath = $basePath === '/' ? '' : $basePath;
                $baseUrl = $protocol . '://' . $host . $basePath;
                
                // Generate configuration file
                $configContent = <<<PHP
<?php
/**
 * Configuration file for Project Linkon
 * Generated by Setup Wizard
 */

return [
    // Database configuration
    'database' => [
        'driver' => 'mysql',
        'host' => '{$dbConfig['host']}',
        'port' => '{$dbConfig['port']}',
        'database' => '{$dbConfig['database']}',
        'username' => '{$dbConfig['username']}',
        'password' => '{$dbConfig['password']}',
        'charset' => 'utf8mb4',
    ],

    // Encryption configuration
    'encryption' => [
        'method' => 'aes-256-gcm',
        'key' => '{$encryptionKey}',
    ],

    // Application configuration
    'app' => [
        'base_url' => '{$baseUrl}',
        'link_length' => 8,
        'debug' => false,
        'cors_origin' => '*',
    ],

    // Password hashing configuration
    'password' => [
        'algo' => PASSWORD_ARGON2ID,
        'options' => [
            'memory_cost' => 65536,
            'time_cost' => 4,
            'threads' => 3,
        ],
    ],
];
PHP;
                
                // Write configuration file
                file_put_contents($configPath, $configContent);
                
                // Create .installed marker file
                file_put_contents($installedPath, date('Y-m-d H:i:s'));
                
                // Clear session
                unset($_SESSION['setup_db_config']);
                
                $success = 'Setup completed successfully!';
                $step = 'complete';
                
            } catch (PDOException $e) {
                $error = 'Setup failed: ' . $e->getMessage();
            } catch (Exception $e) {
                $error = 'Setup failed: ' . $e->getMessage();
            }
        }
    }
}

// Render setup wizard
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Linkon Setup Wizard</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
        }
        .wizard {
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            max-width: 600px;
            width: 100%;
            overflow: hidden;
        }
        .wizard-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem;
            text-align: center;
        }
        .wizard-header h1 {
            font-size: 2rem;
            margin-bottom: 0.5rem;
        }
        .wizard-header p {
            opacity: 0.9;
        }
        .wizard-body {
            padding: 2rem;
        }
        .steps {
            display: flex;
            justify-content: center;
            margin-bottom: 2rem;
            gap: 0.5rem;
        }
        .step-indicator {
            width: 12px;
            height: 12px;
            border-radius: 50%;
            background: #ddd;
        }
        .step-indicator.active {
            background: #667eea;
        }
        .step-indicator.completed {
            background: #28a745;
        }
        h2 {
            font-size: 1.5rem;
            margin-bottom: 1rem;
            color: #333;
        }
        p {
            margin-bottom: 1rem;
            color: #666;
        }
        .form-group {
            margin-bottom: 1.5rem;
        }
        label {
            display: block;
            font-weight: 600;
            margin-bottom: 0.5rem;
            color: #333;
        }
        input[type="text"],
        input[type="password"],
        input[type="number"] {
            width: 100%;
            padding: 0.75rem 1rem;
            border: 2px solid #e1e5eb;
            border-radius: 8px;
            font-size: 1rem;
            transition: border-color 0.2s;
        }
        input:focus {
            outline: none;
            border-color: #667eea;
        }
        .form-row {
            display: grid;
            grid-template-columns: 2fr 1fr;
            gap: 1rem;
        }
        .btn {
            display: inline-block;
            padding: 0.75rem 1.5rem;
            border: none;
            border-radius: 8px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
            text-decoration: none;
        }
        .btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }
        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .btn-secondary {
            background: #6c757d;
            color: white;
        }
        .btn-success {
            background: #28a745;
            color: white;
        }
        .btn-group {
            display: flex;
            gap: 1rem;
            margin-top: 2rem;
        }
        .alert {
            padding: 1rem;
            border-radius: 8px;
            margin-bottom: 1rem;
        }
        .alert-error {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
        .alert-success {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }
        .requirements {
            background: #f8f9fa;
            border-radius: 8px;
            padding: 1rem;
            margin-bottom: 1rem;
        }
        .requirement {
            display: flex;
            justify-content: space-between;
            padding: 0.5rem 0;
            border-bottom: 1px solid #e1e5eb;
        }
        .requirement:last-child {
            border-bottom: none;
        }
        .status-ok { color: #28a745; }
        .status-error { color: #dc3545; }
        .feature-list {
            list-style: none;
            margin: 1rem 0;
        }
        .feature-list li {
            padding: 0.5rem 0;
            padding-left: 1.5rem;
            position: relative;
        }
        .feature-list li::before {
            content: "✓";
            position: absolute;
            left: 0;
            color: #28a745;
            font-weight: bold;
        }
        .generated-key {
            background: #f8f9fa;
            padding: 1rem;
            border-radius: 8px;
            font-family: monospace;
            font-size: 0.85rem;
            word-break: break-all;
            margin: 1rem 0;
        }
        .small-text {
            font-size: 0.85rem;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="wizard">
        <div class="wizard-header">
            <h1>🔗 Linkon Setup</h1>
            <p>Configure your secure link sharing application</p>
        </div>
        
        <div class="wizard-body">
            <?php if ($error): ?>
                <div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div>
            <?php endif; ?>
            
            <?php if ($success && $step !== 'complete'): ?>
                <div class="alert alert-success"><?php echo htmlspecialchars($success); ?></div>
            <?php endif; ?>
            
            <div class="steps">
                <div class="step-indicator <?php echo in_array($step, ['welcome', 'requirements', 'database', 'complete']) ? 'completed' : ''; ?> <?php echo $step === 'welcome' ? 'active' : ''; ?>"></div>
                <div class="step-indicator <?php echo in_array($step, ['requirements', 'database', 'complete']) ? 'completed' : ''; ?> <?php echo $step === 'requirements' ? 'active' : ''; ?>"></div>
                <div class="step-indicator <?php echo in_array($step, ['database', 'complete']) ? 'completed' : ''; ?> <?php echo $step === 'database' ? 'active' : ''; ?>"></div>
                <div class="step-indicator <?php echo $step === 'complete' ? 'completed' : ''; ?> <?php echo $step === 'complete' ? 'active' : ''; ?>"></div>
            </div>
            
            <?php if ($step === 'welcome'): ?>
                <h2>Welcome to Linkon!</h2>
                <p>This wizard will guide you through the setup process for your secure link sharing application.</p>
                
                <ul class="feature-list">
                    <li>AES-256-GCM encryption for all stored content</li>
                    <li>Easy-to-share shortened URLs</li>
                    <li>Minimal user data - only username and password required</li>
                    <li>Full REST API for integration</li>
                </ul>
                
                <p>Before you begin, make sure you have:</p>
                <ul class="feature-list">
                    <li>MySQL or MariaDB database server</li>
                    <li>Database credentials with CREATE TABLE privileges</li>
                    <li>PHP 8.0 or higher with PDO and OpenSSL extensions</li>
                </ul>
                
                <div class="btn-group">
                    <a href="?step=requirements" class="btn btn-primary">Get Started →</a>
                </div>
                
            <?php elseif ($step === 'requirements'): ?>
                <h2>System Requirements</h2>
                <p>Let's check if your server meets the requirements.</p>
                
                <div class="requirements">
                    <?php
                    $phpOk = version_compare(PHP_VERSION, '8.0.0', '>=');
                    $pdoOk = extension_loaded('pdo') && extension_loaded('pdo_mysql');
                    $opensslOk = extension_loaded('openssl');
                    $configWritable = is_writable(dirname($configPath));
                    $allOk = $phpOk && $pdoOk && $opensslOk && $configWritable;
                    ?>
                    <div class="requirement">
                        <span>PHP Version (8.0+)</span>
                        <span class="<?php echo $phpOk ? 'status-ok' : 'status-error'; ?>">
                            <?php echo PHP_VERSION; ?> <?php echo $phpOk ? '✓' : '✗'; ?>
                        </span>
                    </div>
                    <div class="requirement">
                        <span>PDO MySQL Extension</span>
                        <span class="<?php echo $pdoOk ? 'status-ok' : 'status-error'; ?>">
                            <?php echo $pdoOk ? 'Installed ✓' : 'Missing ✗'; ?>
                        </span>
                    </div>
                    <div class="requirement">
                        <span>OpenSSL Extension</span>
                        <span class="<?php echo $opensslOk ? 'status-ok' : 'status-error'; ?>">
                            <?php echo $opensslOk ? 'Installed ✓' : 'Missing ✗'; ?>
                        </span>
                    </div>
                    <div class="requirement">
                        <span>Config Directory Writable</span>
                        <span class="<?php echo $configWritable ? 'status-ok' : 'status-error'; ?>">
                            <?php echo $configWritable ? 'Writable ✓' : 'Not Writable ✗'; ?>
                        </span>
                    </div>
                </div>
                
                <?php if (!$allOk): ?>
                    <div class="alert alert-error">
                        Please fix the above issues before continuing.
                    </div>
                <?php endif; ?>
                
                <div class="btn-group">
                    <a href="?step=welcome" class="btn btn-secondary">← Back</a>
                    <?php if ($allOk): ?>
                        <a href="?step=database" class="btn btn-primary">Continue →</a>
                    <?php endif; ?>
                </div>
                
            <?php elseif ($step === 'database'): ?>
                <h2>Database Configuration</h2>
                <p>Enter your database connection details below.</p>
                
                <form method="POST" action="?step=database">
                    <input type="hidden" name="action" value="test_database">
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="db_host">Database Host</label>
                            <input type="text" id="db_host" name="db_host" value="<?php echo htmlspecialchars($_POST['db_host'] ?? 'localhost'); ?>" required>
                        </div>
                        <div class="form-group">
                            <label for="db_port">Port</label>
                            <input type="text" id="db_port" name="db_port" value="<?php echo htmlspecialchars($_POST['db_port'] ?? '3306'); ?>" required>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_name">Database Name</label>
                        <input type="text" id="db_name" name="db_name" value="<?php echo htmlspecialchars($_POST['db_name'] ?? 'linkon'); ?>" required>
                        <p class="small-text">The database will be created if it doesn't exist.</p>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_user">Database Username</label>
                        <input type="text" id="db_user" name="db_user" value="<?php echo htmlspecialchars($_POST['db_user'] ?? 'root'); ?>" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_password">Database Password</label>
                        <input type="password" id="db_password" name="db_password" value="">
                    </div>
                    
                    <div class="btn-group">
                        <a href="?step=requirements" class="btn btn-secondary">← Back</a>
                        <button type="submit" class="btn btn-primary">Test Connection</button>
                    </div>
                </form>
                
                <?php 
                session_start();
                if ($success && isset($_SESSION['setup_db_config'])): 
                ?>
                    <form method="POST" action="?step=database" style="margin-top: 2rem;">
                        <input type="hidden" name="action" value="complete_setup">
                        
                        <h3 style="margin-bottom: 1rem;">Ready to Install</h3>
                        <p>Connection successful! Click the button below to:</p>
                        <ul class="feature-list">
                            <li>Create database tables</li>
                            <li>Generate secure encryption key</li>
                            <li>Save configuration</li>
                        </ul>
                        
                        <div class="btn-group">
                            <button type="submit" class="btn btn-success">Complete Setup →</button>
                        </div>
                    </form>
                <?php endif; ?>
                
            <?php elseif ($step === 'complete'): ?>
                <h2>🎉 Setup Complete!</h2>
                <p>Linkon has been successfully installed and configured.</p>
                
                <div class="alert alert-success">
                    Your application is ready to use!
                </div>
                
                <p>What you can do now:</p>
                <ul class="feature-list">
                    <li>Create an account to start sharing links</li>
                    <li>Use the API for integrations</li>
                    <li>Customize settings in config/config.php</li>
                </ul>
                
                <div class="btn-group">
                    <a href="/" class="btn btn-primary">Go to Linkon →</a>
                </div>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
